gravitl/netmaker-ui-2

src/constants/ApiRoutes.ts
src/pages/auth/LoginPage.tsx
src/services/BaseService.ts
src/utils/RouteUtils.ts

should be tested after https://github.com/gravitl/netmaker-ui-2/pull/32

clear token and sensitive params

---

src/components/modals/add-client-modal/AddClientModal.tsx
src/components/modals/add-dns-modal/AddDnsModal.tsx
src/components/modals/add-egress-modal/AddEgressModal.tsx
src/components/modals/add-relay-modal/AddRelayModal.tsx
src/components/modals/update-relay-modal/UpdateRelayModal.tsx

more fixes for https://github.com/gravitl/netmaker-ui-2/issues/47

fix: null host/node issue

---

src/components/modals/add-hosts-to-network-modal/AddHostsToNetworkModal.tsx
src/components/modals/add-relay-modal/AddRelayModal.tsx
src/components/modals/update-relay-modal/UpdateRelayModal.tsx
src/constants/Types.ts
src/models/Host.ts
src/models/Node.ts
src/pages/networks/NetworkDetailsPage.tsx
src/services/HostsService.ts
src/services/NodesService.ts
src/services/dtos/CreateHostRelayDto.ts
src/services/dtos/CreateNodeRelayDto.ts
src/store/hosts.ts
src/tests/utils/NodeUtils.test.ts
src/tests/utils/RouteUtils.test.ts
src/tests/utils/Utils.test.ts
src/utils/NodeUtils.ts

DO NOT MERGE UNTIL https://github.com/gravitl/netmaker/tree/relays BRANCH IS MERGED INTO DEVELOP

relay refactor - move from host to node

---

package.json

Net 267 v0.20.2 develop

---

src/components/modals/update-node-modal/UpdateNodeModal.tsx
src/pages/hosts/HostDetailsPage.tsx
src/pages/hosts/NetworkHostDetailsPage.tsx
src/store/hosts.ts
vite.config.ts

- add check for null interface
- ship sourcemaps to all envs

Kwesi/net 387 UI add null check for host interfaces

---

package-lock.json
package.json
src/components/VirtualisedTable.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/tests/fixtures/Models.ts
src/utils/Types.ts

optimise acls page for large number of nodes

---

src/App.tsx
src/components/modals/server-malfunction-modal/ServerMalfunctionModal.tsx

provide detailed reasons and solutions for server errors

feat(NET-491): improve server error msg

---

src/components/NetworkGraph.tsx

fixes https://github.com/gravitl/netmaker-ui-2/issues/215

fix(NET-559): fix for graph edge missing node/client

---

README.md
package.json
release.md

Net 560 update develop

---

website-notes.md

notes on latest release autoretrieval via CORS proxy

chore(NET-529): add website notes

---

index.html
src/App.tsx
src/layouts/MainLayout.tsx
src/models/ServerConfig.ts
src/pages/DashboardPage.tsx
src/pages/auth/LoginPage.tsx
src/pages/enrollment-keys/EnrollmentKeysPage.tsx
src/pages/hosts/NewHostPage.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/pages/users/UsersPage.tsx
src/services/BaseService.ts
src/tests/services/ServerConfigService.test.ts
src/utils/NetworkUtils.ts
src/utils/Utils.tsx

to be tested with https://github.com/gravitl/netmaker/pull/2558

fix(NET-581): check tenant license before applying branding

---

src/pages/hosts/HostDetailsPage.tsx
src/pages/hosts/HostsPage.tsx
src/services/HostsService.ts

feature got lost after git-nastics during last SaaS release cycle to  ship all PRs bar sync feature

chore: restore missing sync feature

---

src/i18n/i18n.ts
src/i18n/resources/de.ts

Added de.ts as of current en.ts

Created de.ts

---

src/pages/networks/NetworkDetailsPage.tsx

allow user to force delete a zombie node. fix subtle bugs

remove pending delete node

---

src/components/modals/update-host-modal/UpdateHostModal.tsx
src/components/modals/update-node-modal/UpdateNodeModal.tsx
src/constants/Types.ts
src/models/Host.ts
src/models/Node.ts
src/pages/hosts/HostDetailsPage.tsx
src/pages/hosts/NetworkHostDetailsPage.tsx
src/routes.tsx
src/tests/fixtures/Models.ts
src/tests/utils/NodeUtils.test.ts
src/tests/utils/RouteUtils.test.ts
src/tests/utils/Utils.test.tsx
src/utils/RouteUtils.ts

move PK from node to host
improve route utils test

move persistent keep alive from node to host

---

scripts/resolve-asset-path.cjs

made a correction in assets path for standalone to fix broken ui after page reload

fix(NET-665): fix broken ui after page reload

---

.github/workflows/publish-qa-builds.yml
src/components/modals/update-host-modal/UpdateHostModal.tsx
src/constants/Types.ts
src/models/Host.ts
src/models/Node.ts
src/pages/hosts/HostDetailsPage.tsx
src/pages/hosts/NetworkHostDetailsPage.tsx
src/tests/fixtures/Models.ts
src/tests/utils/NodeUtils.test.ts
src/tests/utils/RouteUtils.test.ts
src/tests/utils/Utils.test.tsx

add missing auto-upgrade functionality

hotfix v0.21.1 releaese

---

src/components/modals/new-host-modal/NewHostModal.tsx

Adds a docker-compose snippet in adition to the docker run command when adding a docker host.

add docker-compose snippet.

---

src/components/modals/add-egress-modal/AddEgressModal.tsx
src/components/modals/update-egress-modal/UpdateEgressModal.tsx

require default DNS for only internet gateways

hotfix v0.22.0

---

src/components/modals/server-malfunction-modal/ServerMalfunctionModal.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/pages/networks/TourComponent.tsx

- use branding name in server malfunction modal
- improve ux in network details page

NET-966: ux improvements

---

package-lock.json
package.json
src/App.tsx
src/components/modals/add-client-modal/AddClientModal.tsx
src/components/modals/update-egress-modal/UpdateEgressModal.tsx
src/components/modals/update-relay-modal/UpdateRelayModal.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/services/ServerConfigService.ts

- correct health status on modals (relay, egress, rac gw)
- stop annoying ui reload on saas if ui version is already in sync with server version

fix: correct health status on modals, improve ux

---

src/components/modals/add-internet-gateway-modal/AddInternetGatewayModal.styles.scss
src/components/modals/add-internet-gateway-modal/AddInternetGatewayModal.tsx
src/components/modals/add-remote-access-gateway-modal/AddRemoteAccessGatewayModal.tsx
src/components/modals/client-config-modal/ClientConfigModal.tsx
src/components/modals/update-egress-modal/UpdateEgressModal.tsx
src/components/modals/update-internet-gateway-modal/UpdateInternetGatewayModal.styles.scss
src/components/modals/update-internet-gateway-modal/UpdateInternetGatewayModal.tsx
src/components/modals/update-node-modal/UpdateNodeModal.tsx
src/components/modals/update-remote-access-gateway-modal/UpdateRemoteAccessGatewayModal.tsx
src/constants/Types.ts
src/models/Node.ts
src/pages/networks/NetworkDetailsPage.tsx
src/pages/networks/internet-gateways/InternetGatewaysPage.tsx
src/services/NodesService.ts
src/services/dtos/InternetGatewayDto.ts
src/tests/fixtures/Models.ts
src/tests/utils/NodeUtils.test.ts
src/tests/utils/Utils.test.tsx
src/utils/NodeUtils.ts

to be tested with corresponding netclient and server [on ticket](https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/940)

feat(NET-940): internet gateways for hosts

---

package-lock.json
package.json
src/components/modals/version-upgrade-modal/VersionUpgradeModal.styles.scss
src/components/modals/version-upgrade-modal/VersionUpgradeModal.tsx
src/layouts/MainLayout.tsx
src/main.tsx
src/pages/hosts/HostsPage.tsx
src/services/ServerConfigService.ts

add an indicator in the version box to notify users of a new version

feat(NET-1049): notify users of new versions

---

src/constants/ApiRoutes.ts
src/pages/networks/NetworkDetailsPage.tsx
src/pages/users/UsersPage.tsx
src/services/UsersService.ts

oauth/sso users must be approved by an admin before they get access to the server

feat(NET-1064): add gatekeeping for oauth users

---

src/components/modals/client-config-modal/ClientConfigModal.tsx
src/components/modals/client-detaiils-modal/ClientDetailsModal.tsx
src/components/modals/update-remote-access-gateway-modal/UpdateRemoteAccessGatewayModal.tsx
src/constants/Types.ts
src/models/Node.ts
src/pages/hosts/HostsPage.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/services/NodesService.ts
src/tests/fixtures/Models.ts
src/tests/utils/EnrollmentKeysUtils.test.ts
src/tests/utils/NodeUtils.test.ts
src/tests/utils/Utils.test.tsx

this PR enables a user to add additional endpoints for an RAG, and select which to use when connecting with RAC

NET-1106: allow option to set custom endpoints for remote access gateways

---

package-lock.json
package.json
src/components/modals/upgrade-modal/UpgradeModal.tsx
src/constants/LinkAndImageConstants.ts
src/pages/auth/LoginPage.tsx

following server changes, thisPR makes oauth/sso login a pro feature

feat(NET-1134): make sso auth a pro feature

---

src/components/modals/add-network-modal/AddNetworkModal.tsx
src/components/modals/update-node-modal/UpdateNodeModal.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/pages/networks/internet-gateways/InternetGatewaysPage.tsx

- fix node update requiring ipv4 address on a pure ipv6 net
- do not show ipv4 address column on a pure ipv6 net

fix(NET-1240): fix issues with pure ipv6 nets

---

src/components/modals/set-network-failover-modal/SetNetworkFailoverModal.tsx
src/components/modals/update-node-modal/UpdateNodeModal.tsx
src/pages/networks/NetworkDetailsPage.tsx

this PR:
- fixes typos
- improves ux with network host failovers

NET-1233 nmui network hosts tab, failover ux improvement

---

src/components/modals/new-host-modal/NewHostModal.tsx
src/utils/RouteUtils.ts

windows download links should point to exe

patch release v0.24.1

---

src/components/modals/new-host-modal/NewHostModal.tsx
src/utils/RouteUtils.ts

default windows download links to exe bundle

Release v0.24.1 patch rac windows

---

src/components/modals/new-host-modal/NewHostModal.tsx
src/utils/RouteUtils.ts

prefer .exe installer files on windows

patch v0.24.1 on saas-prod

---

package-lock.json
package.json

Reverts gravitl/netmaker-ui-2#627

Revert "build(deps): bump antd from 5.10.3 to 5.18.3"

---

README.md
package.json
release.md
src/services/ServerConfigService.ts

update develop to v0.25.0

---

src/pages/networks/internet-gateways/InternetGatewaysPage.tsx

fix stale glitch in ui after inet client is removed

fix(NET-1512): update node store after updating inet gw

---

src/App.tsx
src/models/ServerConfig.ts
src/services/BaseService.ts
src/store/auth.ts

fix: update intercomId

---

src/App.tsx
src/models/ServerConfig.ts
src/services/BaseService.ts
src/store/auth.ts

This reverts commit 305dd1f5e17ae4e85280d26c00a0f39221e84621.

Revert "feat: add intercomId to baseservice.ts (#824)"

---

src/App.tsx
src/models/ServerConfig.ts
src/services/BaseService.ts
src/store/auth.ts

This reverts commit 316a65802cef716714dd1a48ec0bf195ba2c2d07.

Revert "feat: add intercomId to baseservice.ts"

---

src/components/modals/add-dns-modal/AddDnsModal.tsx

Refactor AddDnsModal to use logical OR operator for value assignment

fix: correct dns ipv6 address selection

---

src/components/modals/add-network-modal/AddNetworkModal.tsx
src/components/modals/new-host-modal/NewHostModal.tsx
src/components/ui/Status.tsx
src/layouts/MainLayout.tsx
src/models/Network.ts
src/models/NodeConnectivityStatus.ts
src/pages/networks/NetworkDetailsPage.tsx
src/pages/networks/NetworksPage.tsx
src/tests/fixtures/Models.ts
src/tests/utils/NetworkUtils.test.ts
src/tests/utils/RouteUtils.test.ts
src/tests/utils/Utils.test.tsx
src/utils/NetworkUtils.ts
src/utils/Utils.tsx

- use display name, a friendlier version of netid
- soften the warnings for private ip range
- add tooltip for network fields
- simplify node statuses

fix: ux enhanments around networks and hosts

---

src/components/modals/add-network-modal/AddNetworkModal.tsx
src/components/modals/new-host-modal/NewHostModal.tsx
src/components/ui/Status.tsx
src/layouts/MainLayout.tsx
src/models/Network.ts
src/models/NodeConnectivityStatus.ts
src/pages/networks/NetworkDetailsPage.tsx
src/pages/networks/NetworksPage.tsx
src/tests/fixtures/Models.ts
src/tests/utils/NetworkUtils.test.ts
src/tests/utils/RouteUtils.test.ts
src/tests/utils/Utils.test.tsx
src/utils/NetworkUtils.ts
src/utils/Utils.tsx

- use display name, a friendlier version of netid
- soften the warnings for private ip range
- add tooltip for network fields
- simplify node statuses

fix: ux enchanments around networks and hosts

---

src/components/RacDownloadBanner.tsx
src/components/modals/add-node-modal/AddNodeDialog.tsx
src/pages/networks/NetworkDetailsPage.tsx
src/pages/users/GroupsPage.tsx
src/pages/users/UserGroupDetailsPage.tsx
src/services/UsersService.ts

- show rac/mobile option only on EE
- fix errors with graph page

Pre-release-fixes-v0.26.0-phase-2

---

Dockerfile.standalone

fix: update base image in Dockerfile from alpine to bookworm-slim

---

.github/workflows/ci.yml
.github/workflows/saas-deploy.yml

update CI and deployment workflows to include release branches and correct PostHog environment variable names

fix: patch ci workflows

---

.github/workflows/saas-deploy.yml

- update saas-deploy workflow to include branch input for deployment

chore: enable saas deployment from any branch
